"""
Django settings for webamcr project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import socket
import dj_database_url

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['WEBAMCR_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['192.168.254.21', '192.168.254.17', '192.168.254.12', 'localhost', '127.0.0.1', '127.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'amcrusers',
    'documents',
    'detectors',
    'crispy_forms',
    'widget_tweaks',
    'django_rq'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webamcr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'base_templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'documents.context_processors.constants_import',
                'documents.context_processors.user_import',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamp': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.environ['WEBAMCR_LOGGING_FILE_PATH'],
            'backupCount': 100,
            'maxBytes': 5242880,
            'formatter': 'timestamp',
            'encoding': 'utf8',
        },
        'file_rq_worker': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/webamcr/rqworker.log',
            'backupCount': 10,
            'maxBytes': 5242880,
            'formatter': 'timestamp'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
        },
        'webamcr.views': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'documents.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'documents.xmlrpc': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'documents.helper': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'documents.decorators': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'detectors.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'detectors.helper': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'detectors.amcemails': {
            "handlers": ['console', 'file_rq_worker'],
            "level": "DEBUG"
        },
        'amcrusers.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'amcrusers.user_helper': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}

WSGI_APPLICATION = 'webamcr.wsgi.application'

DATABASES = {}
DATABASES['default'] = dj_database_url.config(conn_max_age=0)

# Setting environment
HOSTNAME = socket.gethostname()
AMCR_API = ''
DOMAIN_NAME = ''
if (HOSTNAME == 'amc-test'):
    AMCR_API = 'backend-test.aiscr.cz'
    DOMAIN_NAME = 'amcr-test.aiscr.cz'
elif (HOSTNAME == 'amc-tr'):
    AMCR_API = 'api-tr.archeologickamapa.cz'
    DOMAIN_NAME = 'amcr-tr.aiscr.cz'
elif (HOSTNAME == 'amc'):
    AMCR_API = 'backend.aiscr.cz'
    DOMAIN_NAME = 'amcr.aiscr.cz'
elif 'amcr-dev2' in HOSTNAME:
    AMCR_API = '192.168.254.21'
    DOMAIN_NAME = 'amcr-dev2.aiscr.cz'
else:
    AMCR_API = 'backend-dev.aiscr.cz'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'cs'

DEFAULT_CHARSET = 'utf-8'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False
DATE_FORMAT = 'Y-m-d'

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = [
    ('cs', _('Česky')),
    ('en', _('Anglicky')),
]

# Production settings according to deploy audit
SESSION_COOKIE_SECURE = True
#SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "base_static"),
]

# Development options
AMCR_BACKEND_MOCK = False
LOAD_CONSTANTS_FROM_FILE = False

# Jak casto se ma volat endpoint na udrzeni session se servrem (ping->login) / sec
AMCR_LOGIN_INT = 86400  # Na produkci 10 min t.j. 600 s
LOGIN_KEEP_ALIVE = True
INACTIVITY_INTERVAL = 3600  # By how much time extend allowed inactivity time
INACTIVITY_NOTIF_INT = 600  # How much time user has to click on the modal

# Email settings
EMAIL_HOST = 'localhost'
EMAIL_PORT = '25'
EAMIL_USE_TLS = True
EMAIL_USE_SSL = False

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': '127.0.0.1:6379:0',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'MAX_ENTRIES': 5000,
        },
    },
}

RQ_QUEUES = {
    'default': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        #'PASSWORD': 'some-password',
        'DEFAULT_TIMEOUT': 360,
    },
    'high': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 500,
    },
    'low': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
    }
}
